name: Push  Files

on:
  push:
    branches: [ main ]
    paths:
      - 'gef-doc/src/main/resources/**'

jobs:
  push-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with Submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Prepare Target Content
        run: |
          echo "当前工作目录: $(pwd)"
          cd ../
          echo "当前工作目录: $(pwd)"
          mkdir -p target_content
          cp -R gef-framework/gef-doc/src/main/resources/* target_content/

      - name: Push to Target Repository
        uses: actions/github-script@v6
        env:
          TARGET_REPO: "https://${{ secrets.TARGET_PAT }}@github.com/yangfeng-kccs/gef-docs.git"
        with:
          script: |
            const fs = require('fs').promises;
            const { execSync } = require('child_process');
            
            // 获取环境变量
            const targetRepo = process.env.TARGET_REPO;

            console.log("当前目录: " + process.cwd());
            process.chdir("..")
            console.log("当前目录: " + process.cwd());
            // 确保目录不存在
            try {
              await fs.rm('target_repo', { recursive: true, force: true });
              console.log("已删除旧的目标目录");
            } catch (err) {
              console.log("目标目录不存在，无需删除");
            }
            
            console.log("开始克隆目标仓库...");
            execSync(`git clone ${targetRepo} target_repo`, { stdio: 'inherit' });
            
            
            // mkdir -p target_repo/25.9
          
            console.log("清空目标仓库...");
            execSync('find target_repo -mindepth 1 ! -name ".git" -exec rm -rf {} +', { stdio: 'inherit' });
            
            console.log("复制新内容...");
            await fs.cp('target_content', 'target_repo', { recursive: true });
            
            console.log("当前目录: " + process.cwd());
            console.log("切换到目标仓库目录...");
            process.chdir('target_repo');
            
            console.log("当前目录: " + process.cwd());
            execSync('ls -la', { stdio: 'inherit' });
            
            console.log("添加文件...");
            execSync('git add -A', { stdio: 'inherit' });
            
            console.log("检查变更...");
            const status = execSync('git status --porcelain').toString();
            if (!status) {
              console.log("没有变更需要提交");
              return;
            }
            
            console.log("提交变更...");
            execSync('git config user.name "GitHub Actions"', { stdio: 'inherit' });
            execSync('git config user.email "actions@github.com"', { stdio: 'inherit' });
            execSync(`git commit -m "Update s from ${process.env.GITHUB_SHA}"`, { stdio: 'inherit' });
            
            console.log("推送变更...");
            execSync('git push origin main', { stdio: 'inherit' });
            console.log("推送完成!");
