name: Push Docs to External Repo

on:
  push:
    branches: [ main ]  # 触发分支
    paths:
      - 'gef-doc/src/main/resources/**'  # 仅当资源目录变更时触发

jobs:
  push-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 确保子模块被检出
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Target Repo
        env:
          TARGET_REPO: "https://${{ secrets.TARGET_PAT }}@github.com/yangfeng-kccs/gef-docs.git"
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Prepare Target Content
        run: |
          # 创建临时目录并复制资源文件
          mkdir -p target_content
          cp -R gef-doc/src/main/resources/* target_content/

      - name: Push to Target Repository
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs').promises;
            const { execSync } = require('child_process');
            
            // 克隆目标仓库到临时目录
            execSync('git clone https://${{ secrets.TARGET_PAT }}@github.com/yangfeng-kccs/gef-docs.git target_repo', { stdio: 'inherit' });
            
            cd target_repo
            mkdir -p 25.9
            cp -R ../target_content/* .
            
            cd ..
            git add .
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            
            # 检查是否有实际变更
            if git diff-index --quiet HEAD --; then
              echo "No changes to push"
            else
              git commit -m "Update resources from gef-doc (${GITHUB_SHA:0:7})"
              git push origin main
            fi
            
      
